### ISSUE TITLE
"General error: 1364 Field 'transfer_site_id' doesn't have a default value" after running Tsugi database upgrade

### ISSUE THREAD

**Issue by austin48** [cilt-uct/tsugi-migrate-to-brightspace#21]
1. install Sakai Tsugi
2. install tsugi-migrate-to-brightspace into Tsugi
3. login to the Tsugi web app
4. click the Admin tab and login with the Tsugi admin pw
5. click "Upgrade Database"
6. click the Tools tab
7. click the Migrate to Brighspace "Details" button
8. click the "Try it" button
9. error

42000:42000:SQLSTATE[HY000]: General error: 1364 Field 'transfer_site_id' doesn't have a default value

This issue happens because the tsugi-migrate-to-brightspace/database.php script changes **transfer_site_id** column to be "NOT NULL"

Either the database.php script should set the  **transfer_site_id**  column to be "DEFAULT NULL"
Or other places in the code should set / include a value for **transfer_site_id**

**Comment by smarquard** [comment]
In our production db:

  `transfer_site_id` varchar(255) DEFAULT NULL,

**Comment by smarquard** [comment]
Closed by #23
