### ISSUE TITLE
migration_site.lesson_type column error when running Tsugi database upgrade

### ISSUE THREAD

**Issue by austin48** [cilt-uct/tsugi-migrate-to-brightspace#22]
1. install Sakai Tsugi
2. install tsugi-migrate-to-brightspace into Tsugi
3. login to the Tsugi web app
4. click the Admin tab and login with the Tsugi admin pw
5. click "Upgrade Database"
6. error

Upgrading: ALTER TABLE migration_site ADD lesson_type NUM('default', 'single', 'bottom') NOT NULL DEFAULT 'default'
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NUM('default', 'single', 'bottom') NOT NULL DEFAULT 'default'' at line 1

I suspect this happens because the lesson_type should be an enum() instead of a num() in tsugi-migrate-to-brightspace/database.php

**Comment by smarquard** [comment]
We ended up not using lesson_type, so we can remove all references to this field, @npmali  including on the admin tool Add Sites page:

<img width="617" alt="image" src="https://github.com/cilt-uct/tsugi-migrate-to-brightspace/assets/5888197/94a52fbf-3531-4207-b7f9-225ba710f555">

**Comment by smarquard** [comment]
Resolved in #24

**Comment by austin48** [comment]
Thanks!
